services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: chatbot_frontend:latest
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: chatbot_backend:latest
    ports:
      - "8000:8000"
    environment:
      - API_KEY=ee60f033b2409b81cbdfd35da47c2a86
      - JWT_SECRET=617f9d2c597971baaa6c6d2a98b2e42ddb9d189b70aef2320802791743ef9bbf
      - QA_DB_PATH=/app/data/chatbot_data.db
      - REDIS_URL=redis://redis:6379/0
      - THRESH=0.45
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
